### ISSUE TITLE
Build failure on Ubuntu ARM 

### ISSUE THREAD

**Issue by kraiskil** [krrishnarraj/clpeak#2]
clpeak does not build on Ubuntu 13.10 ARM out-of-the box:
kraiskil@notdroid:~/opencl/clpeak/build$ cmake ..
-- The C compiler identification is GNU 4.8.1
-- The CXX compiler identification is GNU 4.8.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Setting build type to Release
-- Selected OpenCL includes from /usr/include
-- Selected OpenCL lib /usr/lib/arm-linux-gnueabihf/libOpenCL.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kraiskil/opencl/clpeak/build
kraiskil@notdroid:~/opencl/clpeak/build$ make
Scanning dependencies of target clpeak
[ 11%] Building CXX object CMakeFiles/clpeak.dir/src/common.cpp.o
In file included from /home/kraiskil/opencl/clpeak/src/include/common.h:7:0,
                 from /home/kraiskil/opencl/clpeak/src/common.cpp:1:
/usr/include/CL/cl.hpp:216:23: fatal error: emmintrin.h: No such file or directory
 #include <emmintrin.h>
                       ^
compilation terminated.
make[2]: **\* [CMakeFiles/clpeak.dir/src/common.cpp.o] Error 1
make[1]: **\* [CMakeFiles/clpeak.dir/all] Error 2
make: **\* [all] Error 2

The cl.hpp is installed via Ubuntu repositories, the opencl-headers package version 1.2-2013.06.28-2. Updating to latest khronos.org cl.hpp does not help or change the error.
